# Generated by Django 5.2.7 on 2025-10-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenciones', '0002_rename_descripcion_trabajo_mantencion_descripcion_realizada_and_more'),
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='fecha_creacion',
            new_name='generado_en',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='titulo',
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivo_pdf',
            field=models.FileField(blank=True, upload_to='reportes/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='mantencion',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Mantenciones.mantencion'),
            preserve_default=False,
        ),
    ]
