# Generated by Django 5.2.7 on 2025-10-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('en_reparacion', 'En Reparación'), ('fuera_servicio', 'Fuera de Servicio')], default='operativo', max_length=20)),
            ],
        ),
    ]
