# Generated by Django 5.2.7 on 2025-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='tipo',
            new_name='categoria',
        ),
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='margen_mantencion_dias',
            field=models.PositiveIntegerField(default=0, help_text='Días hasta que el equipo entra en riesgo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='ultima_mantencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('optimo', 'Óptimo'), ('advertencia', 'Advertencia'), ('critico', 'Crítico'), ('fuera_servicio', 'Fuera de servicio')], default='optimo', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
