# Generated by Django 5.2.7 on 2025-10-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_rename_tipo_equipo_categoria_equipo_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Óptimo', 'Óptimo'), ('Advertencia', 'Advertencia'), ('Critico', 'Crítico'), ('Fuera de Servicio', 'Fuera de Servicio')], default='optimo', max_length=20),
        ),
    ]
