# Generated by Django 5.2.7 on 2025-11-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0003_alter_equipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Óptimo', 'Óptimo'), ('Advertencia', 'Advertencia'), ('Critico', 'Crítico'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Óptimo', max_length=20),
        ),
    ]
