# Generated by Django 5.2.7 on 2025-12-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0004_alter_equipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Óptimo', 'Óptimo'), ('Advertencia', 'Advertencia'), ('Crítico', 'Crítico'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Óptimo', max_length=20),
        ),
    ]
