# Generated by Django 5.2.7 on 2025-10-05 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0001_initial'),
        ('Repuestos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True)),
                ('descripcion_trabajo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='Equipos.equipo')),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantenciones.mantencion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repuestos.repuesto')),
            ],
        ),
        migrations.AddField(
            model_name='mantencion',
            name='repuestos',
            field=models.ManyToManyField(related_name='mantenciones', through='Mantenciones.RegistroUsoRepuesto', to='Repuestos.repuesto'),
        ),
    ]
