# Generated by Django 5.2.7 on 2025-10-30 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_rename_tipo_equipo_categoria_equipo_activo_and_more'),
        ('Mantenciones', '0001_initial'),
        ('Repuestos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantencion',
            old_name='descripcion_trabajo',
            new_name='descripcion_realizada',
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='fecha_realizada',
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='mantencion',
            name='archivos',
            field=models.FileField(blank=True, null=True, upload_to='mantenciones/'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='correos_notificacion',
            field=models.TextField(default=0, help_text='Separar correos por coma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantencion',
            name='descripcion_general',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantencion',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='intervalo_dias',
            field=models.PositiveIntegerField(default=0, help_text='Días hasta la próxima mantención'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantencion',
            name='mantencion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mantenciones.mantencion'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('realizada', 'Realizada'), ('atrasada', 'Atrasada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='fecha_programada',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='RepuestoMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.PositiveIntegerField()),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mantenciones.mantencion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repuestos.repuesto')),
            ],
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='repuestos',
            field=models.ManyToManyField(through='Mantenciones.RepuestoMantencion', to='Repuestos.repuesto'),
        ),
        migrations.DeleteModel(
            name='RegistroUsoRepuesto',
        ),
    ]
