# Generated by Django 5.2.7 on 2025-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenciones', '0002_rename_descripcion_trabajo_mantencion_descripcion_realizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Realizada', 'Realizada'), ('Atrasada', 'Atrasada')], default='pendiente', max_length=20),
        ),
    ]
