# Generated by Django 5.2.7 on 2025-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenciones', '0003_alter_mantencion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En curso', 'En curso'), ('Realizada', 'Realizada'), ('Atrasada', 'Atrasada')], default='Pendiente', max_length=20),
        ),
    ]
