# Generated by Django 5.2.7 on 2025-11-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenciones', '0004_alter_mantencion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mantenciones/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='Mantenciones.mantencion')),
            ],
        ),
    ]
