# Generated by Django 5.2.7 on 2025-11-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mantenciones', '0005_archivomantencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='fecha_realizada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
