# Generated by Django 5.2.7 on 2025-10-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('cantidad_stock', models.PositiveIntegerField(default=0)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
