# Generated by Django 5.2.7 on 2025-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Fecha de Ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='cantidad_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
    ]
