# Generated by Django 5.2.7 on 2025-11-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0002_repuesto_activo_repuesto_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='stock_maximo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
    ]
